---

name: Deploy Images to GHCR

on:
  workflow_dispatch:
  # only to be manually triggered

permissions:
  contents: read

jobs:
  push-devcontainer-image:

    runs-on: ubuntu-latest

    steps:

      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/oytundemirbilek/ml-dev:latest
          docker push ghcr.io/oytundemirbilek/ml-dev:latest
