---

# This workflow will install Python dependencies and lint with a single version of Python
# For more information see:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run pre-commit quality check

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  run-precommit:

    runs-on: ubuntu-latest

    steps:

      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache-venv
        with:
          path: ./.venv/
          key: precommit-venv-${{ hashFiles('pyproject.toml') }}
          restore-keys: precommit-venv-

      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: make dependencies_lint

      - name: Run precommit
        run: make pre-commit-ci
